### ISSUE TITLE
Research bounty events and, eg, subsquid

### ISSUE THREAD

**Issue by morkeltry** [FrankBevr/Things#2]
* Which events are emitted at different stages of the bounty process?
* Are they useful for our purposes?
* What data do they contain?
* What data are they missing?

* How can we access these events through subsquid (or alternative)?
* Will subsquid listen to the chain and provide some live hook we can listen for?
* How do we get detailed info for the events?

**Comment by FrankBevr** [comment]
Issue is already solved via Discord. 

Sidenote:
This Repo was changed to [Quickstart of Futurachy](https://github.com/PolkaHack/futarchy)
Further issues please write further issues [here](https://github.com/PolkaHack/futarchy/issues).
