### ISSUE TITLE
Identify Zeitgeist extrinsics

### ISSUE THREAD

**Issue by morkeltry** [FrankBevr/Things#3]
... which may be of use now or for stretch goals

* Do they have corresponding SDK functions?
* Do they have approval stages or deposits?
* What are the costs?

NB -  if we want to make a DEX or any kind of outcome-outcome swap, we need either to export the tokens offchain (Harald says this is not something they've implemented for outcome tokens), or find some kind of atomic swap functionality across markets (probably doesn't exist either) ... I'm wondering how there is a prize then for 'outcomes DEX' 🤔

**Comment by sgerodes** [comment]
> Do they have corresponding SDK functions?

https://docs.zeitgeist.pm/docs/build/sdk/introduction

**Comment by sgerodes** [comment]
> What are the costs?

Tried to create a market manually:
Total Cost: 1200 ZTG, ca 10 Euro.


Cost Breakdown:

Permissionless Bond
Returned if the market isn't deleted by the committee
1000 ZTG

Oracle
Bond Returned if oracle reports the market outcome on time
200 ZTG

Liquidity 
Can be withdrawn at any time, will collect fees but subject to impermanent loss
0 ZTG

**Comment by sgerodes** [comment]
I can build a module around the Zeitgeist sdk. It will probably have following functions:
createMarket();
readMarked(someId);
