### ISSUE TITLE
Implement login to polkassembly

### ISSUE THREAD

**Issue by morkeltry** [FrankBevr/Things#4]
Implement module which exports a `polkassemblyClient` with `.login()` and `.active()` methods

_______________________________
Navigating and posting in Polkassembly should be easy - it's a graphQL query, with an authentication token in the HTTP header.

The auth token has a one-hour expiry (but seems the clock is out ??)

The site is a non-standard React app (React Dev Tools cannot parse it)

I would guess we need a framework such as Cypress which works well with React to fill in the login form. 
But there may be some way simpler way to do it..

**Comment by morkeltry** [comment]
Maybe `.active()` is better known as `.isLoggedIn()` ;P

**Comment by k-gunjan** [comment]
yea.. its possible using Selenium. i ll make it
